### ISSUE TITLE
fixed x axis scale for MLE.plot

### ISSUE THREAD

**Issue by aquadog7900** [andrew-edwards/sizeSpectra#6]
Hello,
It's a great package, it is really helpful for quickly analyzing and plotting my data.
I'm trying to compare several positions for their respective size spectra (plankton), so I'd like to make a figure with multiple plots using MLE.plot, but would like to control the range on the x-axis so they can be visually comparable. I tried the old xlim, but that didn't work, any suggestions?

**Comment by andrew-edwards** [comment]
Try installing again - the above commit should enable that. Thanks for your comment. Please let me know if it works - if so then just close the Issue!

**Comment by aquadog7900** [comment]
Perfect! Works great, thanks for the update!

**Comment by andrew-edwards** [comment]
Great. Let me know if you want the same for any other plots.
